name = "go"
directory = "{{ .version }}-{{ .platform }}-{{ .arch }}"

[executables]
go="go/bin/go"

[params]
version="1.22.2"
arch="amd64"
platform="linux"

[tarball]
url = "https://go.dev/dl/go{{ .version }}.{{ .platform }}-{{ .arch }}.tar.gz"
